services:
  db:
    image: postgres:16-alpine
    container_name: library-database
    restart: unless-stopped
    ports:
      - "54421:5432"
    environment:
      POSTGRES_DB: library_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: library-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  postgres_db_data: