spring.application.name=library-api

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:54421/library_database
spring.datasource.username=user
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
